[package]
name = "universal_bre"
version = "0.1.0"
authors = ["Jon Fast <jnfstdj656@gmail.com>"]

[dependencies]
termcolor = "0.3.6"
clap = "2.31.2"
rustyline = "1.0.0"
mashup = "0.1"
uuid = { version = "0.6", features = ["v4"] }